################################################################################################################
# GODPEY : DATA CREATION BATCHFILE 
################################################################################################################
#
# Build Masks for sprites
#
################################################################################################################
C:\SOURCE\RG\MASKMAKE\MASKMAKE.TTP C:\SOURCE\RG\HOTPOT\GFX\BALL-GB.PI1 C:\SOURCE\RG\HOTPOT\GFX\MASKS\BALL-GB.PI1
C:\SOURCE\RG\MASKMAKE\MASKMAKE.TTP C:\SOURCE\RG\HOTPOT\GFX\BALL-SPR.PI1 C:\SOURCE\RG\HOTPOT\GFX\MASKS\BALL-SPR.PI1
#C:\SOURCE\RG\MASKMAKE\MASKMAKE.TTP C:\SOURCE\RG\HOTPOT\GFX\FRNT-BTZ.PI1 C:\SOURCE\RG\HOTPOT\GFX\MASKS\FRNT-BTZ.PI1
C:\SOURCE\RG\MASKMAKE\MASKMAKE.TTP C:\SOURCE\RG\HOTPOT\GFX\HI-FONT.PI1 C:\SOURCE\RG\HOTPOT\GFX\MASKS\HI-FONT.PI1
C:\SOURCE\RG\MASKMAKE\MASKMAKE.TTP C:\SOURCE\RG\HOTPOT\GFX\PAUSE.PI1 C:\SOURCE\RG\HOTPOT\GFX\MASKS\PAUSE.PI1
################################################################################################################
#
# Build Palettes
#
################################################################################################################
#C:\SOURCE\RG\PALMAKE\PALMAKE.TTP C:\SOURCE\RG\GODPEY\GFX\CAVE.PI1 C:\SOURCE\RG\GODPEY\DATA\STORY.PAL
################################################################################################################
#
# Build Sprites
#
################################################################################################################
#C:\SOURCE\RG\BSBMAKER\BSBMAKER.TTP C:\SOURCE\RG\GODPEY\BATS\MAKEGFX.SCR
