################################################################################################################
# GODPEY : LINKFILE CREATOR
################################################################################################################
C:\SOURCE\RG\MAKELINK\MAKELINK.TTP C:\SOURCE\RG\HOTPOT\LINK C:\SOURCE\RG\HOTPOT\GAME\GEN.LNK
#C:\SOURCE\RG\MAKELINK\MAKELINK.TTP C:\SOURCE\RG\HOTPOT\INTRO C:\SOURCE\RG\HOTPOT\GAME\INTRO.LNK
################################################################################################################
# PACK LINKFILES
################################################################################################################
#C:\TOOLS\PACK\PACK_ICE.240\ICE_2_4.TTP "$ 1 C:\SOURCE\RG\GODPEY\GAME\*.LNK"

