#ifndef	INCLUDED_R_ACROBATS_H
#define	INCLUDED_R_ACROBATS_H

/* ###################################################################################
#  INCLUDES
################################################################################### */

#include	<GODLIB\BASE\BASE.H>


/* ###################################################################################
#  PROTOTYPES
################################################################################### */

void	RenderAcrobats_Init( void );
void	RenderAcrobats_DeInit( void );
void	RenderAcrobats_GameInit( void );
void	RenderAcrobats_LevelInit( void );
void	RenderAcrobats_Update( void );

void	RenderAcrobats_FadeDown( void );
void	RenderAcrobats_FadeUp( void );
 

/* ################################################################################ */

#endif	/*	INCLUDED_R_ACROBATS_H	*/