#ifndef	INCLUDED_A_MAIN_H
#define	INCLUDED_A_MAIN_H

/* ###################################################################################
#  INCLUDES
################################################################################### */

#include	<GODLIB\BASE\BASE.H>


/* ###################################################################################
#  PROTOTYPES
################################################################################### */

void	AudioMain_Init( void );
void	AudioMain_DeInit( void );

void	AudioMain_SpeakerEnable( void );
void	AudioMain_SpeakerDisable( void );
 

/* ################################################################################ */

#endif	/*	INCLUDED_A_MAIN_H	*/ 