#ifndef	INCLUDED_R_SCORE_H
#define	INCLUDED_R_SCORE_H

/* ###################################################################################
#  INCLUDES
################################################################################### */

#include	<GODLIB\BASE\BASE.H>


/* ###################################################################################
#  PROTOTYPES
################################################################################### */

void	RenderScore_Init( void );
void	RenderScore_DeInit( void );
void	RenderScore_GameInit( void );
void	RenderScore_LevelInit( void );
void	RenderScore_Update( void );


/* ################################################################################ */

#endif	/*	INCLUDED_R_SCORE_H	*/